### ISSUE TITLE
Error Band 

### ISSUE THREAD

**Issue by DroneMesh** [wil3/neuroflight#2]
Hi Wil,

This is great work that you are doing here. I have a question regarding your paper on minimizing motor output oscillations. You talk about the error band that once the quad is in the error band it runs the equation Beta Sigma.

I have setup it up as follows the sum of all the axis errors squared and converted to a negative. After this I have set up my error band as -12 is that close to what you mention.

Thank you

**Comment by wil3** [comment]
Hi @DroneMesh, the error band isn't strictly defined, you can have it as a percentage of the target angular velocity or a fixed value. Its just another parameter in this case for reward shaping.
