### ISSUE TITLE
How to build tensorflow properly

### ISSUE THREAD

**Issue by airopti** [wil3/neuroflight#3]
Hi, Thanks for your excellent work. I am trying to build neuroflight according to your instructions. But I meet some problems when trying build Tensorflow from source with XLA JIT support enable.

```bash
# bazel: 0.10.1
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
``` 
I cannot find built `runtime.o,  xla_compiled_cpu_function.o` file as mentioned in your thesis. Did I miss something? Could you give me some suggestions, thanks a lot.

**Comment by airopti** [comment]
and in Line 385 of  `source.mk`says `INCLUDE_DIRS+=$(ROOT)/lib/main/eigen`, while `$(ROOT)/lib/main/` does not have eigen file

**Comment by airopti** [comment]
I have make through that and build obj/neuroflight_3.3.3_MATEKF722.hex (932.2 KB) successfully. But the hex firmware can't be freshed into F722-std using BetaFlight Configure tool. What did I missed?

**Comment by airopti** [comment]
Downgrad Betaflight Configurator form 10.7.0 to 10.6.0 solve this problem. Thank you.

**Comment by wil3** [comment]
Hey @airopti glad you got it working, thanks for troubleshooting, I'm sure this will be helpful to others. Were you able to flash other betaflight hex files using 10.6.0? I wonder what changed. 

The neuroflight documentation has received far less attention than GymFC, please let me know if anything comes up and I'll try to help.

**Comment by wil3** [comment]
I just checked and I was using version 10.4.1. its surprising to me minor version updates would break flashing of older betaflight versions.

**Comment by airopti** [comment]
In my test, 
- Betaflight Configurator 10.7.0 can flash official `betaflight_4.2.5_STM32F7X2.hex`, while not `betaflight_3.3.3_MATEKF722.hex`. 
- Betaflight Configurator 10.6.0 can flash `betaflight_3.3.3_MATEKF722.hex`
